backend:
  name: github
  repo: BernardMcWeeney/BernardMcWeeney.github.io
  branch: master
  site_domain: mcweeney.ie #silly-figolla-159770.netlify.app

media_folder: "assets/img/media" # Media files will be stored in the repo under images/uploads
public_folder: "/assets/img/media" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
site_url: https://mcweeney.ie
display_url: https://mcweeney.ie
logo_url: https://bernardmcweeney.github.io/assets/img/logo/logo.png

collections:
  - name: "journal" # Used in routes, e.g., /admin/collections/blog
    label: "Journal" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    description: "All the Journal Posts"
    create: true # Allow users to create new documents in this collection
    publish_mode: editorial_workflow
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
     - {label: "Author", name: "author", widget: "string", default: "BernardMcWeeney"}
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Publish Date", name: "date", widget: "datetime"}
     - {
        label: "Featured Image", 
        name: "image", 
        widget: "image"
        }
     - {label: "Post Type", name: "postType", widget: "select", options: ["journal", "music", "tech", "project"], default: ["journal"]}
     - {label: "Category", name: "categories", widget: "string", default: " cat1 cat2 "}
     - {label: "Tag", name: "tags", widget: "string", default: " tag1 tag2 tag3 "}
     - {label: "Pinned", name: "pin", widget: "boolean", default: false}
     - {label: "Mermaid", name: "mermaid", widget: "boolean", default: true}
     - {label: "Summary", name: "summary", widget: "string"}
     - {label: "Body", name: "body", widget: "markdown"}